import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

import Provider from "../components/Provider";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="bg-gradient-to-r p-4 pt-10 font-mono  dark:from-slate-950 dark:to-slate-950 from-pink-400 to-violet-600 grid sm:grid-cols-12 sm:pr-3 gap-6">
            <Sidebar />
            <div className="bg-white dark-bg text-black dark:text-white sm:col-span-9 rounded-lg">
              <Navbar />
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
