import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r p-4 pt-10 font-mono from-pink-400 to-violet-600 grid sm:grid-cols-12 gap-6">
        <Sidebar />
        <div className="bg-white text-black sm:col-span-9 rounded-lg">
          <Navbar />
          {children}
          </div>
      </body>
    </html>
  );
}
